# Jekyll configuration; see https://github.com/mojombo/jekyll/wiki/Configuration
# Note: Jekyll configuration settings may not be respected by GitHub Pages.
# Read the friendly manual: https://help.github.com/articles/using-jekyll-with-pages


# Course-site specific configuration:
course:
  # Enter a base path if needed; not necessary for testing at localhost:4000/
  # or if your site is hosted at a simple URL like http://example.com/
  # But, if something comes after the .com/, you should enter it here.
  # E.g., for http://example.com/530/ you'd enter 530/ for base_path:
  base_path: cdm2019fall/
  # base_path: /
  # E.g., ENGL 536
  number: ENGCMP 610
  name: Composing Digital Media
  university: University of Pittsburgh
  # Keep the description brief, about 140 chars
  description: Making the most of multiple modes
  # E.g., Spring 2013:
  term: Fall 2019
  time: TuTh 2:30-3:45
  room: 435 CL
  instructor:
    name: Benjamin Miller
    office: CL 617-N
    office_hours: Wed/Fri 12:00-1:00pm or by appointment
    email: millerb@pitt.edu
    # No @ before your username; e.g., twitter, not @twitter
    twitter: benmiller314

theme: jekyll-theme-time-machine
